# QC and build 
name: QC and Build

on:
  push:
    branches: [ main ]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  quality_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check all .md files have trailing whitespace
        run: echo find a script to confirm all .md files have trailing whitespace




